export const HOME_PATH = '/'
export const MENU_PATH = '/menu'
export const ORDER_PATH = '/order/:orderId'
export const ORDER_SUCCESS_PATH = '/order-success'
export const ORDERS_PATH = '/orders'
export const CART_PATH = '/cart/:cartId'
export const NOT_FOUND_PATH = '*'
